import React from "react";
import type { Metadata } from "next";
import "@styles/scss/main.scss";
import Header from "@widgets/common/Header";
import Footer from "@widgets/common/Footer";
import TopBar from "@widgets/common/TopBar";

export const metadata: Metadata = {
  title: "Carmel College of Engineering & Technology, Punnapra, Alappuzha",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <TopBar/>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
